info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
server:
  port: 8080
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG