info:
  component: Config Server
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nobodyiam/config-repo

server:
  port: 8888
management:
  context_path: /admin
