info:
  component: Config Server
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: git@github.com:nobodyiam/config-repo.git

server:
  port: 8888
management:
  context_path: /admin

logging:
  file: /opt/logs/spring-cloud-config-demo-server.log